networks:
  shared_network:
    external: true 


services:
  vacancy.db:
    image: postgres:latest
    container_name: vacancy.db
    environment:
      POSTGRES_DB: BaimVacancy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - shared_network
    volumes:
      - vacancy.db.data:/var/lib/postgresql/data

  vacancy.api:
    image: aykhan151618/baim.ms-vacancies:latest
    container_name: vacancy.api
    build:
      context: ./Vacancy.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=vacancy.db;Database=BaimVacancy;Username=postgres;Password=admin;Port=5432;
    networks:
      - shared_network
    ports:
      - "8082:8080"
    depends_on:
      - vacancy.db
    volumes:
      - /home/azureuser/home/baim/files:/app/images

volumes:
   vacancy.db.data:
