version: '3.8'

networks:
  shared_network:
    external: true 

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ARnold151618&
    ports:
      - "5672:5672"  # Port for RabbitMQ
      - "15672:15672" # Port for RabbitMQ Management UI
    networks:
      - shared_network