networks:
  shared_network:
    external: true

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: {{RABBITMQ_LOGIN}}
      RABBITMQ_DEFAULT_PASS: {{RABBITMQ_PASSWORD}}
    ports:
      - "5672:5672"  # Port for RabbitMQ
      - "15672:15672" # Port for RabbitMQ Management UI
    networks:
      - shared_network
