networks:
  shared_network:
    external: true

services:
  marketing.db:
    image: postgres:latest
    container_name: marketing.db
    environment:
      POSTGRES_DB: BaimMarketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - shared_network
    volumes:
      - marketing.db.data:/var/lib/postgresql/data

  marketing.api:
    image: aykhan151618/baim.ms-marketing:latest
    container_name: marketing.api
    build:
      context: ./Marketing.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=marketing.db;Database=BaimMarketing;Username=postgres;Password=admin;Port=5432;
    networks:
      - shared_network
    ports:
      - "8081:8080"
    depends_on:
      - marketing.db
    volumes:
      - /home/Aykhan2004/home/baim/baim-images/Default:/app/images

volumes:
   marketing.db.data:
