networks:
  default:
    driver: bridge

services:
  personalaccount.db:
    image: postgres:latest
    container_name: personalaccount.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BaimAgile
    ports:
      - "5435:5432"
    networks:
      - default
    volumes:
      - personalaccount.db.data:/var/lib/postgresql/data

  personalaccount.api:
    image: aykhan151618/baim.ms-account:latest
    container_name: personalaccount.api
    build:
      context: ./PersonalAccount.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=personalaccount.db;Database=BaimAgile;Username=postgres;Password=admin;Port=5432;
    networks:
      - default
    ports:
      - "8083:8080"
    depends_on:
      - personalaccount.db
    volumes:
      - /home/azureuser/home/baim/files:/app/images

volumes:
   personalaccount.db.data:
